CREATE DATABASE FinalSis457Jazm;

GO
CREATE LOGIN [usrfinal] WITH PASSWORD=N'12345678',
	DEFAULT_DATABASE=[FinalSis457Jazm],
	CHECK_EXPIRATION=OFF,
	CHECK_POLICY=ON

GO
USE [FinalSis457Jazm]
GO 
CREATE USER [usrfinal] FOR LOGIN [usrfinal]
GO
ALTER ROLE [db_owner] ADD MEMBER [usrfinal]
GO